---
title: C++中的异常处理
author: AshGrey
date: 2024-09-06 00:00:00 +0800
categories: [Computer Science, Language]
tags: [Computer Science, C++]
---

> 本文章所属领域：
>
> [实践产业知识 - 工业产业 - 计算机科学 - 编程语言 - C++]({% post_url /Computer Science/2024-02-08-计算机科学：索引笔记 %})
>
> 本文章所需前置知识：
>
> - [C++基础知识]({% post_url /Computer Science/Language/2024-02-08-C++基础知识笔记 %})
{: .prompt-info}

<br>

## 1 try-catch 语句

<br>

程序运行时经常出现一些异常情况，如果不能发现并进行处理，很可能会导致程序崩溃。所谓的「异常处理」可能是给出错误提示信息，并让程序沿着一条不会出错的路径继续执行；也可能是不得不结束程序，但是在结束前做一些必要的工作。C++ 的异常处理机制的基本思想是：函数 A 在执行过程中发现异常时可以不作处理，而是抛出一个异常给函数 A 的调用者，可以视作一个函数 B。抛出异常不加处理会导致函数 A 立即中止，在这种情况下函数 B 可以捕获 A 抛出的异常进行处理，也可以不加处理抛给 B 的调用者，以此类推。如果一层层的函数都不处理异常，异常最终会抛给最外层的`main()`函数，如果`main()`函数也不处理异常，程序就会立即异常地中止。

<br>

C++ 中完整的异常处理方式如下：
- `throw`表达式，异常处理部分使用`throw`表达式来表示其遇到了无法处理的问题，称作`throw`引发了异常；
- `try`语句块，异常处理部分使用`try`语句块处理异常，其以关键字`try`开始，并以一个或者多个`catch`子句结束，`try`语句块中代码抛出的异常通常会被某个`catch`子句处理，`catch`子句中的代码也被称作异常处理代码；
- 标准库的异常类，用于在`throw`表达式和祥光的`catch`子句间传递异常的具体信息。